### ISSUE TITLE
Write a Makefile

### ISSUE THREAD

**Issue by Anatoliy6463** [Anatoliy6463/Andesaurux#2]
I NEED THIS STUPID MAKEFILE

**Comment by Anatoliy6463** [comment]
It works bad

**Comment by Anatoliy6463** [comment]
Ok, so, i'm working on it now

**Comment by Anatoliy6463** [comment]
@Lulu-Games would you help?

**Comment by Lulu-Games** [comment]
I only know CMAKE
I have not ever written a Make file

**Comment by Anatoliy6463** [comment]
> I only know CMAKE I have not ever written a Make file

Cmake is a script that will be launched by Makefile. If you will create cmake script, i will need to make Makefile launch it.
Makefile is just a shell script with subdivisions

**Comment by Lulu-Games** [comment]
Sorry, I don't have experience with that. And I am currently working on SisijaFight

**Comment by Lulu-Games** [comment]
If you need python code or the package manager, I can help you

**Comment by Anatoliy6463** [comment]
Ok

**Comment by Anatoliy6463** [comment]
OK, so, I've fixing the Makefile and the init system.

**Comment by Anatoliy6463** [comment]
Oh, i doesn't work because bootloader doesn't work, CLOSE WITH COMMENT
